obstacle_range: 2.5
raytrace_range: 3.5
# footprint: [[-0.45, -0.32], [-0.45, 0.32], [0.45, 0.32], [0.45, -0.32]]
robot_radius: 0.5
inflation_radius: 0.3
cost_scaling_factor: 0.5
map_type: costmap
transform_tolerance: 0.2
observation_sources: scan
scan: {data_type: LaserScan, topic: scan, marking: true, clearing: true}